### ISSUE TITLE
Symfony 3 compatibility?

### ISSUE THREAD

**Issue by ppounder** [fkrauthan/FkrSimplePieBundle#13]
Is it possible to ensure Symfony 3.0.x compatibility?

**Comment by fkrauthan** [comment]
This bundle should have no big dependencies to Symfony itself. Unfortunately I don't use it anymore. But feel free to test it out and send pr's in case something is broken.

**Comment by fkrauthan** [comment]
Ok version 1.0.5 was just tagged and contains merge request #14 which suppose to add Symfony3 support. Please test and let me know if there are any issues.
